run:
  timeout: 5m
  issues-exit-code: 0
  tests: false

linters:
  enable:
    - gofmt
    - goimports

linters-settings:
  gofmt:
    simplify: true

issues:
  max-issues-per-linter: 0
  new: false
