---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: wlrobbi@stsgym.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vimi
  namespace: vimi
  labels:
    app: vimi
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-read-timeout: '300'
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - vimi.stsgym.com
    secretName: vimi-tls
  rules:
  - host: vimi.stsgym.com
    http:
      paths:
      - path: /csw
        pathType: Prefix
        backend:
          service:
            name: data-catalog
            port:
              number: 8087
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: vimi-plugin
            port:
              number: 8091
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vimi-plugin
  namespace: vimi
  labels:
    app: vimi
    component: vimi-plugin
  annotations: {}
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - vimi-plugin.stsgym.com
    secretName: vimi-plugin-tls
  rules:
  - host: vimi-plugin.stsgym.com
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: vimi-plugin
            port:
              number: 8091
